### PR TITLE
converted to browserify using 6to5ify. added new options

### PR DESCRIPTION
**Pull request by ericponto**
Not a huge refactor, but made quite a few changes, mostly trying to set up to be able to use more thing from grunticon. Right now it's just using some templates, but could potentially use more in the future.

I also added the template option to customize the CSS template and the dynamicColorOnly option.

I think this should also work with the new embed feature, if it was just a change to the JS file, as this is now pulling the JS straight from grunticon.

### CODE REVIEW

**Comment by jefflembeck** [comment]
Ok, so - 

If you start this with a fresh install, it blows up - namely because bower was removed (yay), but then we're not dealing with the dependencies necessary.

```
Running "browserify:build" (browserify) task
>> Error: Cannot find module 'underscore' from '/Users/jlembeck/Dropbox/code/grumpicon/public/js'
```

I'll put those in the package.json and deal with the copying over

**Comment by jefflembeck** [comment]
Or maybe I'll just have browserify reference them from their new place. Probably an even better idea.

**Comment by ericponto** [comment]
Sorry. Maybe I didn't get package.json update correctly for browserify...
Or I could have an import wrong.

**Comment by jefflembeck** [comment]
it's all good now. Fixed and running locally. I'll get it merged in with master and see if we can't get it up. This codebase looks great (such a treat to be able to use ES6), thank you.

**Comment by ericponto** [comment]
Yes, ES6! I was going to go a little further with it (using some new methods like `Array.from` or `Object.asign`), but didn't want to have to include the polyfill library.

**Pull request merged**
